import { useState } from "react";
import { ArrowUpRight, Clock3, Instagram, Mail, MapPin, Menu, MessageCircle, Sparkles, X } from "lucide-react";

const baseWhatsApp = "https://wa.me/917477471806";
const heroWhatsApp = `${baseWhatsApp}?text=${encodeURIComponent("Hi Meal with Mallick, I'd like to know more about your restaurant.")}`;
const faqs = [
  ["How can I contact Meal with Mallick?", "Message us on WhatsApp at 7477471806 or email maifujulmallick9@gmail.com."],
  ["Where are you located?", "We are based in Citi Egra, West Bengal, India. Use the Google Maps link below for directions."],
  ["What are your opening hours?", "We are open Tuesday to Sunday from 12:00 PM to 11:00 PM."],
  ["Can I ask about availability or special requests?", "Yes. Send us a WhatsApp message and we will reply with current information and availability."]
];

export default function Home() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [mobileOpen, setMobileOpen] = useState(false);
  const scrollTo = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); setMobileOpen(false); };

  return <div className="site-shell">
    <div className="topline"><span>Open today · 12:00 PM — 11:00 PM</span><span className="topline-right">Citi Egra · West Bengal <Sparkles size={13} /></span></div>
    <header className="nav-wrap"><nav className="nav container"><button className="brand" onClick={() => scrollTo("home")} aria-label="Meal with Mallick home"><span className="brand-mark">M</span><span>Meal <i>with</i> Mallick</span></button><div className={`nav-links ${mobileOpen ? "is-open" : ""}`}><button onClick={() => scrollTo("story")}>Our story</button><button onClick={() => scrollTo("location")}>Location</button><button onClick={() => scrollTo("faq")}>FAQs</button><a href={heroWhatsApp} target="_blank" rel="noreferrer" className="nav-cta"><MessageCircle size={16} /> WhatsApp us</a></div><button className="mobile-toggle" onClick={() => setMobileOpen(!mobileOpen)} aria-label="Toggle menu">{mobileOpen ? <X /> : <Menu />}</button></nav></header>
    <main>
      <section className="hero" id="home"><img className="hero-image" src="/manus-storage/hero_f1d25d3e.jpg" alt="A candlelit restaurant table" /><div className="hero-overlay" /><div className="hero-content container"><div className="eyebrow light"><span className="eyebrow-line" /> A table worth gathering around</div><h1>Good food.<br /><em>Better stories.</em></h1><p className="hero-copy">A warm, welcoming table in Citi Egra for good conversations, thoughtful hospitality, and memorable moments.</p><div className="hero-actions"><a className="button button-gold" href={heroWhatsApp} target="_blank" rel="noreferrer"><MessageCircle size={18} /> Connect on WhatsApp <ArrowUpRight size={16} /></a><button className="text-link light" onClick={() => scrollTo("story")}>Discover our story <span>↓</span></button></div></div><div className="hero-note">01 <span /> Thoughtfully hosted. Warmly remembered.</div></section>
      <section className="intro section-pad" id="story"><div className="container intro-grid"><div><div className="eyebrow"><span className="eyebrow-line" /> The Mallick table</div><h2>A place to pause.<br /><em>A reason to stay.</em></h2></div><div className="intro-copy"><p>Meal with Mallick is a hospitality project built around warmth, connection, and the simple joy of sharing time together. We believe a memorable experience begins with making every guest feel at home.</p><p>For current updates, availability, or a personal request, reach out directly. We would love to hear from you.</p><a className="text-link" href={heroWhatsApp} target="_blank" rel="noreferrer">Talk to us on WhatsApp <ArrowUpRight size={16} /></a></div></div><div className="container stat-row"><div><strong>01</strong><span>Warm, personal service</span></div><div><strong>24/7</strong><span>Easy WhatsApp contact</span></div><div><strong>01</strong><span>Local Citi Egra table</span></div></div></section>
      <section className="quote-section"><div className="container quote-grid"><div className="quote-mark">“</div><blockquote>Come as guests,<br /><em>leave as friends.</em></blockquote><div className="quote-aside"><span className="eyebrow"><span className="eyebrow-line" /> A note from us</span><p>Every visit is an invitation to slow down, connect, and make a little more room for good stories.</p></div></div></section>
      <section className="location-section section-pad" id="location"><div className="container location-grid"><div><div className="eyebrow"><span className="eyebrow-line" /> Find us</div><h2>Made in <em>Citi Egra.</em><br />Made for you.</h2><p className="location-copy">Meal with Mallick brings a warm local experience to Citi Egra, West Bengal. Contact us before visiting for the latest availability and directions.</p><div className="location-details"><div><MapPin size={18} /><span><strong>Citi Egra</strong><small>West Bengal, India</small></span></div><div><Clock3 size={18} /><span><strong>Tuesday — Sunday</strong><small>12:00 PM — 11:00 PM</small></span></div></div><a className="button button-dark" href="https://www.google.com/maps/search/?api=1&query=Citi+Egra+West+Bengal" target="_blank" rel="noreferrer"><MapPin size={16} /> Open in Google Maps <ArrowUpRight size={15} /></a></div><div className="map-card"><div className="map-orbit orbit-one" /><div className="map-orbit orbit-two" /><div className="map-pin"><MapPin size={28} /></div><span className="map-label">MEAL WITH MALLICK<br /><small>CITI EGRA, WEST BENGAL</small></span></div></div></section>
      <section className="faq-section section-pad" id="faq"><div className="container faq-grid"><div><div className="eyebrow"><span className="eyebrow-line" /> Good to know</div><h2>Your questions,<br /><em>answered.</em></h2><p className="faq-intro">Still curious? We’re only a message away.</p><a href={heroWhatsApp} target="_blank" rel="noreferrer" className="text-link">Ask us on WhatsApp <ArrowUpRight size={16} /></a></div><div className="faq-list">{faqs.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? "open" : ""}`} key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{String(index + 1).padStart(2, "0")}</span>{question}<b>{openFaq === index ? "−" : "+"}</b></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></div></section>
    </main>
    <footer className="footer"><div className="container footer-grid"><div><button className="brand footer-brand" onClick={() => scrollTo("home")}><span className="brand-mark">M</span><span>Meal <i>with</i> Mallick</span></button><p>Good food. Better stories.<br />Citi Egra, West Bengal.</p></div><div className="footer-links"><span>Connect</span><a href="tel:7477471806">7477471806</a><a href="mailto:maifujulmallick9@gmail.com">maifujulmallick9@gmail.com</a><a href={heroWhatsApp} target="_blank" rel="noreferrer">WhatsApp us <ArrowUpRight size={14} /></a></div><div className="footer-links"><span>Follow along</span><a href={heroWhatsApp} target="_blank" rel="noreferrer"><Instagram size={15} /> Instagram</a><a href="mailto:maifujulmallick9@gmail.com"><Mail size={15} /> Email us</a></div></div><div className="container footer-bottom"><span>© 2026 Meal with Mallick</span><span>Created by Maifujul Mallick</span></div></footer>
  </div>;
}
